name: Continuous Integration
run-name: Testing the build of a Docker image and running the container on ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    paths:
      - src/Dockerfile
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  run:
    name: Run Docker Container
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder"
