name: Continuous Integration
run-name: Testing the build of a Docker image and running the container on ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    paths:
      - src/Dockerfile
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: hello-world:latest
          outputs: type=docker,dest=/tmp/hello-world.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world
          path: /tmp/hello-world.tar
  run:
    name: Run Docker Container
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder"
