name: Continuous Integration
run-name: ${{ github.ref_name }} - ${{ github.event.head_commit.message }}
on:
  push:
    paths:
      - src/Dockerfile
      - hands-on/**/Dockerfile
      - .github/workflows/continuous-integration.yaml
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: hello-world:latest
          outputs: type=docker,dest=/tmp/hello-world.tar
          context: ./src
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world
          path: /tmp/hello-world.tar
  run:
    name: Run Docker Container
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world
          path: /tmp
      - name: Run Container
        run: |
          docker load --input /tmp/hello-world.tar
          docker run hello-world:latest