name: Inform updating personal main branches
run-name: Updating Personal Main Branches on ${{ github.ref_name }}
on:
  push:
    branches:
      - main
      - infra/38 # Todo remove this branch
jobs:
  update_personal_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Retrieve All Personal Branches Matching `**/main`
        id: list_branches
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const branches = await github.paginate(
                github.rest.repos.listBranches,
                {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                }
            )
            const personalMainBranches = branches
                .filter(branch => branch.name.endsWith('/main'))
                .map(branch => branch.name)
            
            if (personalMainBranches.length === 0) {
                core.notice('No personal main branches found.')   
            } else {
                core.notice(`Found personal main branches: ${personalMainBranches.join(', ')}`)
            }
            
            core.setOutput('branches', JSON.stringify(personalMainBranches))